### ISSUE TITLE
v1.3 iOS is almost finished

### ISSUE THREAD

**Issue by tigpt** [AWSary/AWSary-Android#1]
Hi @lzcalderaro

I've been working on v1.3 for iOS, it adds the option of labels on logos like we talked on slack before.

This makes the diagrams more readable specially on services that the logos are not that iconic, and once diagram starts becoming more complex.

For this I added a settings to enable or disable logos on services, and like you suggested, once logos are enabled, I hide the label on the navigation list to avoid names duplication, it becomes more pleasing on the eye.

You can already preview it on the public beta in TestFlight: https://testflight.apple.com/join/V29zWbIF

You think this is easily implemented on Android?

Also I added a white ring on the logos placeholder once the phone is in dark mode, to make the label separation more visible in dark mode, take a look bellow.

Ask me I any question.

![image](https://github.com/AWSary/AWSary-Android/assets/43767/5288ca36-5a0d-4f0e-abf2-76e28a0eda08)
![image](https://github.com/AWSary/AWSary-Android/assets/43767/7798721f-ccc3-47fe-bf4e-cdf084bc7f1e)

**Comment by lzcalderaro** [comment]
@tigpt  I added this feature on my side, and I will publish the new version.

**Comment by tigpt** [comment]
Awesome!
